export interface Application {
        id?: number,
        thumbImg?: string,
        thumbAlt?: string,
        largeImg?: string,
        largeAlt?: string,
        heading?: string,
        name?: string;
        applicationDetail?: string,
        powerRange?: string,
        rationRange?: string,
        stage?: string,
        drive?: string,
        sizeRange?: string,
        reductionRatioRange?: string,
        shaft?: string,
        outputShaft?: string,
        inputOutputShaft?: string,
        mounting?: string,
        additionalAccessories?: string,
        type?: string,
        applications?: string,
        accessories?: string,
        lubrication?:  string,
        screwSizeRange?: string
}
